### PR TITLE
platform independent download path

### LINKED ISSUE #29: How do you set the GAIA_TOOLS_DATA Environment Variable on Windows
I am getting the following error: 
'Environment variable `GAIA_TOOLS_DATA` is not set. '
RuntimeError: Environment variable `GAIA_TOOLS_DATA` is not set. This is required to define where the Gaia data are downloaded to. See the readme: https://github.com/jobovy/gaia_tools#data-files-and-environment-variables for more information.

The readme file neatly explains what the environment variable is, but not how to set it. I have tried setting the environment variables through system properties on Windows but without success.

### PR DESCRIPTION
**Pull request by henrysky**
This PR fixes issue #29 by introducing platform independent download path

### CODE REVIEW

**Comment by jobovy** [comment]
Cool, thanks! Another option would be to use ``pathlib`` and then ask for the path as a ``POSIXpath``? Not sure whether there is any advantage though!

I'm not going to be able to test this on Windows, so I'll have to depend on you to make sure this works on Windows...

**Comment by henrysky** [comment]
At least 

```python
import gaia_tools.load as gload
tgas_cat= gload.tgas()
rc_cat= gload.apogeerc()
```

runs fine without error on my machine and I have never used ``pathlib`` so I dunno if there is any advantage...

**Comment by jobovy** [comment]
Thanks! And this was running with new downloads of the data? (just checking!).

Yes, I haven't used ``pathlib`` either, I just found something that said it was the new, better alternative to ``os.path``...

**Comment by henrysky** [comment]
Yes new downloads, I have deleted local tgas data long time ago. And I see ``gaia_tools`` downloads APOGEE RC in gaia folder instead of using existing apogee rc in apogee folder, is this a expected behavior?

**Comment by jobovy** [comment]
Great!

If you have ``apogee`` installed and its environment variables set up, ``gaia_tools`` is supposed to fall back onto the ``apogee`` data folders... 

I'll merge once I have a minute to test on Mac.

**Pull request merged**
